data:
    type: "LoadDatasets"
    task: "inpainting"
    train_dataset: "CelebaHQ"
    val_dataset: "CelebaHQ"
    patch_size: 128
    channels: 3
    num_workers: 4
    data_dir: "./CycleRDM/data"
    ckpt_dir: "ckpt/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200
    num_diffusion_timesteps_1: 100

training:
    batch_size: 4
    n_epochs: 1000
    validation_freq: 1000

optim:
    weight_decay: 0.0001
    optimizer: "Adam"
    lr: 0.00008
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8
